import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
import MobileDetector from "./components/mobile-detector";

const satoshi = localFont({
  src: '../public/fonts/Satoshi-Regular.woff2',
  display: 'swap'
})

export const metadata: Metadata = {
  title: "Machine Learning Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${satoshi.className} antialiased`}
      > 
        <MobileDetector />
        <div className = "relative z-10">
          {children}
        </div>
      </body>
    </html>
  );
}
